### ISSUE TITLE
Bug of generating circle

### ISSUE THREAD

**Issue by 2020-cai** [neperfepx/neper#483]
========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.
Info   : Version 4.0.2
Info   : Built with: gsl|muparser|opengjk|nlopt
Info   : <http://neper.info>
Info   : Copyright (C) 2003-2020, and GNU GPL'd, by Romain Quey.
Info   : ---------------------------------------------------------------
Info   : MODULE  -T loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] -n 100 -morpho
         diameq:0.71*lognormal(8,0.5)+0.21*lognormal(8,0.5)+0.08*lognormal(8,0.5)
         -regularization 1 -dim 2 -domain circle(50.8) -group mode -o BC
Info   : ---------------------------------------------------------------
Info   : Reading input data...
Info   : Creating domain...
Info   : Creating tessellation...
Info   :   - Setting seeds... 100%
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :     > Initial solution: f   =16.695844393
Info   :     > Iteration   6451: fmin=0.000004945 f=0.000004953
Info   :     > Reached `eps' criterion.
Info   : Regularizing tessellation...
Info   :   - loop 1/2:  65% del=51Error  : You have discovered a bug in Neper!  Please file an issue at
         https://github.com/rquey/neper/issues.  Thank you.

Aborted

**Comment by rquey** [comment]
Thanks @2020-cai for the bug report.

For a circular domain, regularization generally cannot be pushed as far as for a standard, square domain. Use `-rsel 0.5` to stop it earlier (it has failed at 65%, so it can theoretically be pushed to close to 0.65).
