### ISSUE TITLE
diameq:costum(mydistrib) -> missing sigma error

### ISSUE THREAD

**Issue by jrorschach** [neperfepx/neper#561]
**diameq:costum(mydistrib) -> missing sigma error**

Specifying an Experimental Cell Size Distribution with external distribution file ```-morpho "diameq:costum(mydistrib)"``` aborts with ```missing sigma``` message

**To Reproduce**

Following the instructions on https://neper.info/tutorials/morpho_statistics.html I try to load my own diameq distribution, but neper 4.4.1 and 4.5.1-1 aborts the tessellation because it misses a sigma. Am I missing something here?

Thanks in advance.

See the command and error below:

```
$ neper -T -n from_morpho -dim 3 -domain "cube(1.,1.,1.)" -morpho "diameq:costum(mydistrib)"

========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.
Info   : Version 4.5.1-1
Info   : Built with: gsl|muparser|opengjk|openmp|nlopt|libscotch (full)
Info   : Running on 16 threads.
Info   : <https://neper.info>
Info   : Copyright (C) 2003-2022, and GNU GPL'd, by Romain Quey.
Info   : ---------------------------------------------------------------
Info   : MODULE  -T loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] -n from_morpho -dim 3 -domain cube(1.,1.,1.) -morpho
         diameq:costum(mydistrib)
Info   : ---------------------------------------------------------------
Info   : Reading input data...
Info   : Creating domain...
Info   : Creating tessellation...
Error  : costum(mydistrib): missing sigma
Aborted
```

The ```mydistrib``` file consists of the following lines (same as in https://neper.info/tutorials/morpho_statistics.html):
```
0.2 10.0
0.3 20.0
0.4 5.0
```

**Comment by rquey** [comment]
You wrote `costum` instead of `custom`.

**Comment by jrorschach** [comment]
well, using the correct words helps, sorry and thank you
