### ISSUE TITLE
Bug in Neper

### ISSUE THREAD

**Issue by Siamak-Shiahvan** [neperfepx/neper#649]
I am using the command:
neper -T -n 120 -reg 1 -domain "sphere(10,100)"
and getting:
========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.
Info   : Version 4.5.1-1
Info   : Built with: gsl|muparser|opengjk|nlopt|libscotch
Info   : <https://neper.info>
Info   : Copyright (C) 2003-2022, and GNU GPL'd, by Romain Quey.
Info   : No initialization file found (`/home/siamak/.neperrc').
Info   : ---------------------------------------------------------------
Info   : MODULE  -T loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] -n 120 -reg 1 -domain sphere(10,100)
Info   : ---------------------------------------------------------------
Info   : Reading input data...
Info   : Creating domain...
Info   : Creating tessellation...
Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   : Regularizing tessellation...
Info   :   - loop 1/2:  17% del=139Error  : You have discovered a bug in Neper!  Please file an issue at
         https://github.com/rquey/neper/issues.  Thank you.

**Comment by rquey** [comment]
Regularization sometimes fail for domains such as spheres.

You can try to use a different `-id`, to see if it gets to larger percentages.

Knowing the percentage at failure, you can use `-rsel` to stop regularization earlier. In your case, use `-rsel 0.17`.
During meshing, it may be necessary to increase the value of `-pl` to avoid local refinements.
