### ISSUE TITLE
Pole figure generating issue

### ISSUE THREAD

**Issue by majidmech** [neperfepx/neper#676]
Hi @rquey 
I have installed the latest version of Neper and I was trying to plot some pole figures from the neper Tutorials. At first I had the issue that no images were generating. Then, I installed asymptote. But I'm getting the following error now (I have also installed texlive-full):

```
 neper -V n100.tess -space pf -print img2

========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.
Info   : Version 4.5.1-4
Info   : Built with: gsl|muparser|opengjk|openmp|nlopt|libscotch (full)
Info   : Running on 16 threads.
Info   : <https://neper.info>
Info   : Copyright (C) 2003-2022, and GNU GPL'd, by Romain Quey.
Info   : No initialization file found (`/home/majidkavousi/.neperrc').
Info   : ---------------------------------------------------------------
Info   : MODULE  -V loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] n100.tess -space pf -print img2
Info   : ---------------------------------------------------------------
Info   : Loading tessellation...
Info   :     [i] Parsing file `n100.tess'...
Info   :     [i] Parsed file `n100.tess'.
Info   : Printing pole figure...
Info   :   - Computing symbols...
Info   :   - Generating png file (1200x900 pixels)...
Info   :     [o] Writing file `img2.png'...
Wrong __data_start/_end pair
Aborted (core dumped)
Info   :     [o] Wrote file `img2.png'.
Info   : Printing scale...
Info   : Elapsed time: 0.161 secs.
```

Do you have any idea on this issue?

**Comment by rquey** [comment]
`Wrong __data_start/_end pair` is not a Neper message - likely something from Asymptote.

Is `img2.png` generated? If not, try to run this to see if anything special pops up:
```
neper -V n100.tess -space pf -imageformat asy -print img2
asy -f pdf img2.asy                                # converts  to pdf
asy -f png -render 10 img2.asy                     # converts to png
```

**Comment by majidmech** [comment]
No image gets generated. I tried these commands. I'm getting the same error.

$ neper -V n100.tess -space pf -imageformat asy -print img2

========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.
Info   : Version 4.5.1-4
Info   : Built with: gsl|muparser|opengjk|openmp|nlopt|libscotch (full)
Info   : Running on 16 threads.
Info   : <https://neper.info>
Info   : Copyright (C) 2003-2022, and GNU GPL'd, by Romain Quey.
Info   : No initialization file found (`/home/majidkavousi/.neperrc').
Info   : ---------------------------------------------------------------
Info   : MODULE  -V loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] n100.tess -space pf -imageformat asy -print img2
Info   : ---------------------------------------------------------------
Info   : Loading tessellation...
Info   :     [i] Parsing file `n100.tess'...
Info   :     [i] Parsed file `n100.tess'.
Info   : Printing pole figure...
Info   :     [o] Writing file `img2.asy'...
Info   :   - Computing symbols...
Info   :     [o] Wrote file `img2.asy'.
Info   : Printing scale...
Info   : Elapsed time: 0.074 secs.
========================================================================

$ asy -f pdf img2.asy
Wrong __data_start/_end pair
Aborted (core dumped)
$ asy -f png -render 10 img2.asy
Wrong __data_start/_end pair
Aborted (core dumped)

**Comment by rquey** [comment]
So, as you can see, it is an Asymptote issue. It must not be installed properly.
