### ISSUE TITLE
Model visualization is returning an error

### ISSUE THREAD

**Issue by kshankar7** [neperfepx/neper#746]
I created a structured mesh (following the guidelines in https://neper.info/doc/fileformat.html#mesh-file-msh) and was successful when I do not assign grain ids to the mesh `tag1` & `tag2` and set them to the same value of 1 for all elements. When I assign a grain id to each element (same value for `tag1` and `tag2`). My intention is visualize the mesh. While the first mesh produces an image, the second one does not and returns an error. Can you help. Both the mesh files are attached and the image output from the first command is shown below.

Successful command
`neper -V tet4_without_grain_id.msh -print img`

Unsuccessful command
`neper -V tet4_with_grain_id.msh -print img`

[tet4_mesh.zip](https://github.com/neperfepx/neper/files/12549369/tet4_mesh.zip)

![img](https://github.com/neperfepx/neper/assets/86091354/f3254c11-85e7-4841-a9cc-f4d74340c915)

```
========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.
Info   : Version 4.5.1-127-devel
Info   : Built with: gsl|muparser|opengjk|openmp|nlopt|libscotch (full)
Info   : Running on 96 threads.
Info   : <https://neper.info>
Info   : Copyright (C) 2003-2022, and GNU GPL'd, by Romain Quey.
Info   : No initialization file found (`/home/kshankar/.neperrc').
Info   : ---------------------------------------------------------------
Info   : MODULE  -V loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] tet4_with_grain_id.msh -print img
Info   : ---------------------------------------------------------------
Info   :   - Reading arguments...
Info   : Loading mesh...
Info   :     [i] Parsing file `tet4_with_grain_id.msh'...
Info   :     [i] Parsed file `tet4_with_grain_id.msh'.
Info   : Reconstructing mesh...
Info   :     > Reconstructing 2D mesh... 100%      
Info   :     > Reconstructing 1D mesh... 100%      
Info   :     > Reconstructing 0D mesh... 100%      
Error  : You have discovered a bug in Neper!  Please file an issue at
         https://github.com/rquey/neper/issues.  Thank you.

Aborted (core dumped)
```

**Comment by rquey** [comment]
It fails to reconstruct the topology.  The workaround to this is to add
```
$Topology
0
$EndTopology
```
at the top of your file, as described in [Mesh File(`.msh`)](https://neper.info/doc/fileformat.html#mesh-file-msh).

Then:
```
neper -V tet4_with_grain_id.msh -print img

========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.
Info   : Version 4.6.1-8
Info   : Built with: gsl|muparser|opengjk|openmp|nlopt|libscotch (full)
Info   : Running on 16 threads.
Info   : <https://neper.info>
Info   : Copyright (C) 2003-2022, and GNU GPL'd, by Romain Quey.
Info   : Loading initialization file `/home/rquey/.neperrc'...
Info   : ---------------------------------------------------------------
Info   : MODULE  -V loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] tet4_with_grain_id.msh -print img
Info   : ---------------------------------------------------------------
Info   :   - Reading arguments...
Info   : Loading mesh...
Info   :     [i] Parsing file `tet4_with_grain_id.msh'...
Info   :     [i] Parsed file `tet4_with_grain_id.msh'.
Info   : Printing image...
Info   :   - Printing mesh...
Info   :     > Reducing data...
Info   :       . 3D...
Info   :       . 2D...
Info   :       . Number of 3D elt faces reduced by  95% (to 1200).
Info   :       . Number of 3D elt edges reduced by  50% (to 1800).
Info   :   - Generating png file (1200x900 pixels)...
Info   :     [o] Writing file `img.png'...
Info   :     [o] Wrote file `img.png'.
Info   : Printing scale...
Info   : Elapsed time: 1.027 secs.
========================================================================
```

![img](https://github.com/neperfepx/neper/assets/2659376/8038182e-ace6-4d20-b726-e986ce41722e)

**Comment by kshankar7** [comment]
Thank you. It works, but I still have issues with the following command (trying to increase the tet order, with topology included as outlined above). Let me try to see if there are similar workarounds (for the same mesh files)
Successful Command
`neper -M -loadmesh tet4_without_grain_id.msh -order 2 -o tet10_without_grain_id`

Unsuccessful Command
`neper -M -loadmesh tet4_with_grain_id.msh -order 2 -o tet10_with_grain_id`

**Comment by rquey** [comment]
Can you share a smaller mesh?  (2 x 2 x 2 polycrystal)

**Comment by kshankar7** [comment]
Sure (sorry for the delay, had to go to a class). Please find attached.
![Small](https://github.com/neperfepx/neper/assets/86091354/fb6efcc3-d2eb-4920-8564-dba87f6020be)
[small_mesh.zip](https://github.com/neperfepx/neper/files/12551171/small_mesh.zip)

**Comment by rquey** [comment]
It is the same mesh. Anyway, here is a problem:
```
neper -V tet4_with_grain_id.msh -showelset "id==1" -print img
```
![d](https://github.com/neperfepx/neper/assets/2659376/30e2e52f-b726-441c-ae92-e2a4f9e91d91)

A grain must be a contiguous set of elements, otherwise, Neper fails to reconstruct the topology.
