### ISSUE TITLE
3D meshing fails ' failed_polys' file generated.

### ISSUE THREAD

**Issue by 18nanma** [neperfepx/neper#904]
2D Meshing goes through, but 3D meshing fails ' failed_polys' file generated.

gmsh installed correctly, neper tesselation generation is also fine.

neper -M n10-id1.tess

========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.
Info   : Version 4.9.0
Info   : Built with: gsl|muparser|opengjk|openmp|nlopt|libscotch (full)
Info   : Running on 1 threads.
Info   : <https://neper.info/>
Info   : Copyright (C) 2003-2022, and GNU GPL'd, by Romain Quey.
Info   : Ignoring initialization file.
Info   : ---------------------------------------------------------------
Info   : MODULE  -M loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] n100-id1.tess -mesh3dclreps 1
Info   : ---------------------------------------------------------------
Info   : Reading input data...
Info   :   - Reading arguments...
Info   : Loading input data...
Info   :   - Loading tessellation...
Info   :     [i] Parsing file `n100-id1.tess'...
Info   :     [i] Parsed file `n100-id1.tess'.
Info   : Meshing...
Info   :   - Preparing... (cl = 0.1077) 100%
Info   :   - 0D meshing... 100%
Info   :   - 1D meshing... 100%
Info   :   - 2D meshing... 100% (0.045|0.64/96%| 3%| 1%)
Info   :   - Fixing 2D-mesh pinches...
Info   :   - 3D meshing... Info   :     [o] Writing file `failed_polys'...
Info   :     [o] Wrote file `failed_polys'.
Error  : Meshing failed

**Comment by rquey** [comment]
You forgot this part:

> **To Reproduce**
> 
> Provide a *minimal working example* that can be used to reproduce the bug, that is, *complete* but *excluding unnecessary options*, *large inputs* and *excessive computation times*.  The example should include the program commands and other necessary input, and the terminal output.
> 
> *Formatting is important*.  An example should be written as *plain text* (no screenshot, etc.) and provided between triple backticks (Markdown formatting).  Input or output text files that are too large to be provided in-text can be attached (GitHub requires a .txt extension).  Images can be used if necessary.
> 
> To preview your message, use "Preview".  To edit your message after it is published, use "Edit".

**Comment by 18nanma** [comment]
Thank you so much for the quick response nad for creating this awesome software.
so the msh works for eltype hex and quad but not for tri or tet

! neper -T -n 10 -dim 3
! neper -V n10-id1.tess -datacellcol id -print Image_1
! neper -M n10-id1.tess -elttype hex
========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.
Info   : Version 4.9.0
Info   : Built with: gsl|muparser|opengjk|openmp|nlopt|libscotch (full)
Info   : Running on 1 threads.
Info   : <https://neper.info/>
Info   : Copyright (C) 2003-2022, and GNU GPL'd, by Romain Quey.
Info   : No initialization file found (`/root/.neperrc').
Info   : ---------------------------------------------------------------
Info   : MODULE  -M loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] n10-id1.tess -elttype hex
Info   : ---------------------------------------------------------------
Info   : Reading input data...
Info   :   - Reading arguments...
Info   : Loading input data...
Info   :   - Loading tessellation...
Info   :     [i] Parsing file `n10-id1.tess'...
Info   :     [i] Parsed file `n10-id1.tess'.
Info   : Meshing...
Info   :   - Preparing... (cl = 0.09999) 100%

Info   :   - 3D meshing... 100%
Info   :   - Switching mesh to order 2...
Info   : Searching nsets and fasets...
Info   : Writing mesh results...
Info   :   - Preparing mesh...
Info   :   - Mesh properties:
Info   :     > Node number:     4961
Info   :     > Elt  number:     1000
Info   :     > Mesh volume:    1.000
Info   :   - Writing mesh...
Info   :     [o] Writing file `n10-id1.msh'...
Info   :     [o] Wrote file `n10-id1.msh'.
Info   : Elapsed time: 0.125 secs.
========================================================================

!neper -M n10-id1.tess -rcl 0.5  -order 2 -elttype tet
========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.
Info   : Version 4.9.0
Info   : Built with: gsl|muparser|opengjk|openmp|nlopt|libscotch (full)
Info   : Running on 1 threads.
Info   : <https://neper.info/>
Info   : Copyright (C) 2003-2022, and GNU GPL'd, by Romain Quey.
Info   : No initialization file found (`/root/.neperrc').
Info   : ---------------------------------------------------------------
Info   : MODULE  -M loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] n10-id1.tess -rcl 0.5 -order 2 -elttype tet
Info   : ---------------------------------------------------------------
Info   : Reading input data...
Info   :   - Reading arguments...
Info   : Loading input data...
Info   :   - Loading tessellation...
Info   :     [i] Parsing file `n10-id1.tess'...
Info   :     [i] Parsed file `n10-id1.tess'.
Info   : Meshing...
Info   :   - Preparing... (cl = 0.116) 100%
Info   :   - 0D meshing... 100%
Info   :   - 1D meshing... 100%
Info   :   - 2D meshing... 100% (0.3|0.86/85%|10%| 5%)
Info   :   - Fixing 2D-mesh pinches...
I**nfo   :   - 3D meshing... Info   :     [o] Writing file `failed_polys'...
Info   :     [o] Wrote file `failed_polys'.
Error  : Meshing failed**

[37]
4s
!neper -V n10-id1.tess,n10-id1.msh -print img2

**Comment by 18nanma** [comment]
very interesting,
I followed an earlier post of using older gmsh command and it works.(newer one doesn't)
!neper -T -n 100 -id 1 -format geo
!gmsh -format msh2 -3 n100-id1.geo

the gmsh version i currently use is 4.8.4

**Comment by rquey** [comment]
Your Gmsh installation must be broken somehow. Everything works here with Gmsh 4.8.4.

**Comment by 18nanma** [comment]
I use Colab, that might be the issue.
Thanks for your promt response and contribution
