### ISSUE TITLE
Add the possibility of lamellae in the case of cubic grain morphology

### ISSUE THREAD

**Issue by sylm21** [neperfepx/neper#914]
I don't know if this is a bug or a feature that isn't present, but I'd like to know if it's possible to generate lamellae in a cubic grain morphology. I've tried a few commands like :

 neper -T -n from_morpho -morpho "cube(5),lamellar(w=0.1)"

or

neper -T -n from_morpho -morpho "cube(5)::lamellar(w=0.1)"

Thanks in advance

**Comment by rquey** [comment]
```
neper -T -n from_morpho::from_morpho -morpho "cube(5)::lamellar(w=0.05)" -o d
neper -V d.tess -print img
```
![img](https://github.com/user-attachments/assets/579112c4-dc66-4984-a9fe-0c0f41a8c962)

**Comment by sylm21** [comment]
Thanks a lot
